name: kds_sample_project
description: "A sample project for a KDS system, based on certain requirements for an interview."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/sample_data.json